"""create role tables

Revision ID: 1f153bcd10b7
Revises: 7d2920a07a59
Create Date: 2025-12-29

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1f153bcd10b7'
down_revision: Union[str, Sequence[str], None] = '7d2920a07a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_role_is_deleted'), table_name='role')
    op.create_index(op.f('ix_role_is_deleted'), 'role', ['is_deleted'], unique=False)
    op.alter_column('user_role', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_role', 'user_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user_role', 'role_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user_role', 'club_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('idx_user_role_is_deleted'), table_name='user_role')
    op.drop_index(op.f('idx_user_role_role_id'), table_name='user_role')
    op.drop_index(op.f('idx_user_role_user_id'), table_name='user_role')
    op.create_index(op.f('ix_user_role_is_deleted'), 'user_role', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_role_role_id'), 'user_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_user_id'), 'user_role', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role_user_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_role_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_is_deleted'), table_name='user_role')
    op.create_index(op.f('idx_user_role_user_id'), 'user_role', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_role_role_id'), 'user_role', ['role_id'], unique=False)
    op.create_index(op.f('idx_user_role_is_deleted'), 'user_role', ['is_deleted'], unique=False)
    op.alter_column('user_role', 'club_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
    op.alter_column('user_role', 'role_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False)
    op.alter_column('user_role', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False)
    op.alter_column('user_role', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_role_is_deleted'), table_name='role')
    op.create_index(op.f('idx_role_is_deleted'), 'role', ['is_deleted'], unique=False)
    op.alter_column('role', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
